on: [push]
branches:
    - feature/central-server

env:
    AWS_REGION: 'ca-central-1'
    IMAGE_TAG: 'cs-v7.6.1'

jobs:
    build_publish_image:
        runs-on: ubuntu-latest
        name: A job to build and publish the image to AWS ECR

        permissions:
            id-token: write
            # packages: write

        steps:
            - uses: actions/checkout@v4

            - id: build
              name: 'Build and publish the image to AWS ECR'
              #uses: yonepv/hello-world-composite-action/publish-image-to-registry@main
              uses: CQEN-QDCE/ceai-cqen-commons/actions/aws/publish-image-to-ecr@feature/actions
              with:
                aws-region: ${{ env.AWS_REGION }}
                role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                registry: ghcr.io
                image-name: ${{ inputs.IMAGE_TAG }}-${{ github.run_number }}
                working-directory: .
                    
                

