on: 
    #[push]
    workflow_dispatch:

jobs:
    build_publish_image:
        runs-on: ubuntu-latest
        name: A job to build and publish the image to a registry

        permissions:
            attestations: write
            id-token: write
            packages: write

        steps:
            #- uses: actions/checkout@v4

            - id: build
              name: Build the image
              #uses: yonepv/hello-world-composite-action/publish-image-to-registry@V1.1
              uses: yonepv/hello-world-composite-action/publish-image-to-registry@feature/wip-adjust-common-script-push-to-registry
              with:
                registry: ghcr.io
                image-name: ${{ github.repository }}-${{ github.run_number }}
                github-token: ${{ secrets.GITHUB_TOKEN }}         

