name: Test environment output variables in action

on: 
    workflow_dispatch:   
    push:
        paths:
            - .github/workflows/test-env-output-vars-in-action.yml                   

jobs:
  test_env_output_vars_in_action:
    runs-on: ubuntu-latest
    name: A job to test environment output variables in action
    steps:
      - name: Set local environment variables
        id: setLocalEnvVars
        run: |
          echo "Setting local environment variables..."
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
      - name: Print local environment variables
        id: printLocalEnvVars
        run: |
          echo "Printing local environment variables set in the previous step:"
          echo "REPO_NAME: ${{ env.REPO_NAME }} or $REPO_NAME"
          echo "RUN_NUMBER: ${{ env.RUN_NUMBER }} or $RUN_NUMBER"
          echo $REPO_NAME
          echo $RUN_NUMBER          
