name: Test environment output variables in action
'on':
  - push
jobs:
  test_env_output_vars_in_action:
    runs-on: ubuntu-latest
    name: A job to test environment output variables in action
    steps:
      - name: Set local environment variables
        id: setLocalEnvVars
        run: >
          echo "Setting local environment variables..."
          echo "ENV_VAR_REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo $ENV_VAR_REPO_NAME
          echo "ENV_VAR_RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo $ENV_VAR_RUN_NUMBER
      - name: Print local environment variables
        id: printLocalEnvVars
        run: |
          echo "Printing local environment variables set in the previous step:"
          echo "ENV_VAR_REPO_NAME=${{ env.ENV_VAR_REPO_NAME }}"
          echo "ENV_VAR_RUN_NUMBER=${{ env.ENV_VAR_RUN_NUMBER }}"
  call-to-push-to-registry:
    runs-on: ubuntu-latest
    name: Call to push to registry

    steps:
        - name: Call to push to registry
          #uses: yonepv/hello-world-composite-action/publish-image-to-registry@feature/wip-adjust-common-script-push-to-registry
          uses: MCN-CQEN/ceai-cqen-commons/actions/publish-image-to-registry@feature/wip-add-params-repo-to-push-image-to-registry
          with:
            registry: ghcr.io
            image-name: ${{ env.ENV_VAR_REPO_NAME }}-${{ env.ENV_VAR_RUN_NUMBER }}
            github-token: '${{ secrets.GITHUB_TOKEN }}'       
            push-to-registry: false     
        - name: Print docker images
          run: |
            echo "Printing docker images..."
            docker images
